language: node_js
node_js:
- "10"
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
- yarn bootstrap
script:
- yarn build
- yarn run check
- yarn test
- yarn build:doc
- git commit -am "Fake commit of generated docs"
after_script:
- yarn test:coverage
- yarn test:coveralls
before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script: "yarn lerna:publish"
  skip_cleanup: true
  on:
    node: "10"
    tags: true
