language: node_js
node_js:
- "10"
before_script:
- npm run bootstrap
script:
- npm run build
- npm run check
- npm run test
after_script:
- npm run test:coverage
- npm run test:coveralls
before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script: "npm run lerna:publish"
  skip_cleanup: true
  on:
    node: "10"
    tags: true

