language: node_js
node_js:
- "10"
script:
- npm run bootstrap
- npm run check
# - npm run build
- npm run lerna run prepublish
after_script:
- npm run test:coverage
- npm run test:coveralls
before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: scripts
  scripts: "npm run lerna:publish"
  skip_cleanup: true
  on:
    node: "10"
    tags: true
    branch: master

