name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:  
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install dependencies
        run: yarn bootstrap

      - name: Build
        run: yarn build
      
      - name: Lint
        run: yarn lint
      
      - name: Unit tests
        run: yarn test
